export const POKEMON_TYPE_COLORS = {
    normal: { type_ko: "노말", color: "#A8A77A" },
    fire: { type_ko: "불꽃", color: "#EE8130" },
    water: { type_ko: "물", color: "#6390F0" },
    electric: { type_ko: "전기", color: "#F7D02C" },
    grass: { type_ko: "풀", color: "#7AC74C" },
    ice: { type_ko: "얼음", color: "#96D9D6" },
    fighting: { type_ko: "격투", color: "#C22E28" },
    poison: { type_ko: "독", color: "#A33EA1" },
    ground: { type_ko: "땅", color: "#E2BF65" },
    flying: { type_ko: "비행", color: "#A98FF3" },
    psychic: { type_ko: "에스퍼", color: "#F95587" },
    bug: { type_ko: "벌레", color: "#A6B91A" },
    rock: { type_ko: "바위", color: "#B6A136" },
    ghost: { type_ko: "고스트", color: "#735797" },
    dragon: { type_ko: "드래곤", color: "#6F35FC" },
    dark: { type_ko: "악", color: "#705746" },
    steel: { type_ko: "강철", color: "#B7B7CE" },
    fairy: { type_ko: "페어리", color: "#D685AD" },
} as const;
